repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 'v1.64.0'
  hooks:
    - id: checkov
      args: [
        "--skip-check", "CKV_AWS_18", 
        "--skip-check", "CKV_AWS_19", 
        "--skip-check", "CKV_AWS_21", 
        "--skip-check", "CKV_AWS_144",  
        "--skip-check", "CKV_AWS_145",
      ]
    # - id: infracost_breakdown
    #   args:
    #     - --args=--path=./env/dev
    #   verbose: true
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_tflint
      args:
        - --args=--enable-rule=terraform_documented_variables
    - id: terraform_tfsec
